<?php

return [
    'sections' => [
        'overview' => [
            'label'       => 'Overview',
            'description' => 'Priority shortcuts for day-to-day platform monitoring',
            'icon'        => 'dashboard',
            'color'       => 'primary',
            'items'       => [
                'dashboard' => [
                    'label'       => 'Dashboard',
                    'description' => 'View core analytics, balances, and operational highlights',
                    'route'       => 'admin.dashboard',
                    'icon'        => 'dashboard',
                    'color'       => 'primary',
                    'keywords'    => ['overview', 'analytics', 'home'],
                ],
                'transactions' => [
                    'label'       => 'Transactions',
                    'description' => 'Monitor platform-wide money movement and payment activity',
                    'route'       => 'admin.transaction',
                    'permission'  => 'transaction-list',
                    'icon'        => 'transaction-2',
                    'color'       => 'primary',
                    'keywords'    => ['payments', 'history', 'logs'],
                ],
                'activity_logs' => [
                    'label'       => 'Activity Logs',
                    'description' => 'Review system actions and important user activity records',
                    'route'       => 'admin.activity-log',
                    'permission'  => 'user-activity-log',
                    'icon'        => 'user-activity',
                    'color'       => 'secondary',
                    'keywords'    => ['audit', 'monitoring', 'logs'],
                ],
            ],
        ],
        'account_operations' => [
            'label'       => 'Account Operations',
            'description' => 'Manage users, merchants, access levels, and account health',
            'icon'        => 'user-management',
            'color'       => 'info',
            'items'       => [
                'all_users' => [
                    'label'       => 'All Users',
                    'description' => 'Manage registered user accounts and profile status',
                    'route'       => 'admin.user.index',
                    'permission'  => 'user-list',
                    'icon'        => 'users-1',
                    'color'       => 'info',
                    'badge'       => 'Users',
                    'keywords'    => ['accounts', 'members', 'profiles'],
                ],
                'active_users' => [
                    'label'       => 'Active Users',
                    'description' => 'Review currently active customer accounts',
                    'route'       => 'admin.user.active',
                    'permission'  => 'user-list',
                    'icon'        => 'active-users',
                    'color'       => 'success',
                    'badge'       => 'Users',
                    'keywords'    => ['active', 'customers', 'status'],
                ],
                'suspended_users' => [
                    'label'       => 'Suspended Users',
                    'description' => 'Handle restricted or suspended account records',
                    'route'       => 'admin.user.suspended',
                    'permission'  => 'user-list',
                    'icon'        => 'banned-users',
                    'color'       => 'danger',
                    'badge'       => 'Users',
                    'keywords'    => ['blocked', 'disabled', 'status'],
                ],
                'merchant_reviews' => [
                    'label'       => 'Pending Merchants',
                    'description' => 'Review merchant onboarding requests and approvals',
                    'route'       => 'admin.merchant.pending',
                    'permission'  => 'merchant-list',
                    'icon'        => 'merchant-alert',
                    'color'       => 'warning',
                    'badge'       => 'Merchants',
                    'keywords'    => ['merchant', 'approval', 'pending'],
                ],
                'all_merchants' => [
                    'label'       => 'All Merchants',
                    'description' => 'Manage merchant accounts, shops, and business records',
                    'route'       => 'admin.merchant.index',
                    'permission'  => 'merchant-list',
                    'icon'        => 'merchant',
                    'color'       => 'success',
                    'badge'       => 'Merchants',
                    'keywords'    => ['business', 'merchant', 'shops'],
                ],
                'user_ranks' => [
                    'label'       => 'User Ranks',
                    'description' => 'Configure rank rules, progression, and user benefits',
                    'route'       => 'admin.ranking.index',
                    'permission'  => 'ranking-manage',
                    'feature_key' => 'user_ranks',
                    'icon'        => 'ranking',
                    'color'       => 'secondary',
                    'badge'       => 'Users',
                    'keywords'    => ['tiers', 'levels', 'benefits'],
                ],
            ],
        ],
        'compliance_marketplace' => [
            'label'       => 'Compliance & Marketplace',
            'description' => 'Control KYC workflows and P2P marketplace operations',
            'icon'        => 'kyc',
            'color'       => 'warning',
            'items'       => [
                'kyc_queue' => [
                    'label'       => 'Awaiting KYC',
                    'description' => 'Process newly submitted KYC verification requests',
                    'route'       => 'admin.kyc.pending',
                    'permission'  => 'kyc-list',
                    'icon'        => 'kyc-alert',
                    'color'       => 'warning',
                    'badge'       => 'KYC',
                    'keywords'    => ['verification', 'documents', 'pending'],
                ],
                'kyc_records' => [
                    'label'       => 'KYC Records',
                    'description' => 'Access the full history of KYC submissions and decisions',
                    'route'       => 'admin.kyc.index',
                    'permission'  => 'kyc-list',
                    'icon'        => 'identification',
                    'color'       => 'info',
                    'badge'       => 'KYC',
                    'keywords'    => ['kyc', 'history', 'verification'],
                ],
                'p2p_dashboard' => [
                    'label'       => 'P2P Dashboard',
                    'description' => 'Monitor marketplace performance, trades, and activity',
                    'route'       => 'admin.p2p.index',
                    'permission'  => 'p2p-manage',
                    'icon'        => 'p2p_trading',
                    'color'       => 'primary',
                    'badge'       => 'P2P',
                    'keywords'    => ['marketplace', 'trading', 'offers'],
                ],
                'p2p_disputes' => [
                    'label'       => 'P2P Disputes',
                    'description' => 'Handle trade disputes and marketplace escalations',
                    'route'       => 'admin.p2p.disputes.index',
                    'permission'  => 'p2p-dispute-manage',
                    'icon'        => 'support',
                    'color'       => 'danger',
                    'badge'       => 'P2P',
                    'keywords'    => ['disputes', 'claims', 'trades'],
                ],
                'p2p_payment_methods' => [
                    'label'       => 'P2P Payment Methods',
                    'description' => 'Manage available payment methods for marketplace offers',
                    'route'       => 'admin.p2p.methods.index',
                    'permission'  => 'p2p-method-manage',
                    'icon'        => 'payment',
                    'color'       => 'success',
                    'badge'       => 'P2P',
                    'keywords'    => ['payment methods', 'marketplace', 'offers'],
                ],
            ],
        ],
        'wallet_payments' => [
            'label'       => 'Wallet & Payments',
            'description' => 'Manage financial products, methods, and transaction channels',
            'icon'        => 'wallet-cog',
            'color'       => 'success',
            'items'       => [
                'currencies' => [
                    'label'       => 'Currencies',
                    'description' => 'Configure supported currencies and conversion setup',
                    'route'       => 'admin.currency.index',
                    'permission'  => 'currency-manage',
                    'icon'        => 'currency-exchange',
                    'color'       => 'success',
                    'keywords'    => ['currency', 'exchange', 'rates'],
                ],
                'payment_gateways' => [
                    'label'       => 'Payment Gateways',
                    'description' => 'Manage deposit gateway credentials and availability',
                    'route'       => 'admin.payment.gateway.index',
                    'permission'  => 'payment-gateway-list',
                    'icon'        => 'payment-gateway',
                    'color'       => 'primary',
                    'keywords'    => ['gateway', 'provider', 'payment'],
                ],
                'deposit_history' => [
                    'label'       => 'Deposit History',
                    'description' => 'Review deposit requests, statuses, and settlement flow',
                    'route'       => 'admin.deposit.history',
                    'permission'  => 'deposit-list',
                    'icon'        => 'deposit-history',
                    'color'       => 'success',
                    'badge'       => 'Deposits',
                    'keywords'    => ['deposits', 'funding', 'history'],
                ],
                'withdraw_history' => [
                    'label'       => 'Withdraw History',
                    'description' => 'Track withdrawal activity and processing records',
                    'route'       => 'admin.withdraw.history',
                    'permission'  => 'withdraw-list',
                    'icon'        => 'withdraw-log',
                    'color'       => 'danger',
                    'badge'       => 'Withdrawals',
                    'keywords'    => ['withdrawals', 'cashout', 'history'],
                ],
                'virtual_cards' => [
                    'label'       => 'Virtual Cards',
                    'description' => 'Access issued cards, requests, and card lifecycle tools',
                    'route'       => 'admin.virtual-card.list',
                    'permission'  => 'virtual-card-list',
                    'icon'        => 'virtual-card',
                    'color'       => 'info',
                    'badge'       => 'Cards',
                    'keywords'    => ['cards', 'issuance', 'virtual'],
                ],
                'virtual_card_providers' => [
                    'label'       => 'Card Providers',
                    'description' => 'Configure provider connectivity and virtual card setup',
                    'route'       => 'admin.virtual-card.provider.index',
                    'permission'  => 'virtual-card-provider-manage',
                    'icon'        => 'provider',
                    'color'       => 'secondary',
                    'badge'       => 'Cards',
                    'keywords'    => ['providers', 'integration', 'cards'],
                ],
                'referrals' => [
                    'label'       => 'Referrals',
                    'description' => 'Monitor referral campaigns, rewards, and growth data',
                    'route'       => 'admin.referral.index',
                    'permission'  => 'referral-manage',
                    'icon'        => 'referral',
                    'color'       => 'warning',
                    'keywords'    => ['referral', 'rewards', 'growth'],
                ],
                'subscription_plans' => [
                    'label'       => 'Subscription Plans',
                    'description' => 'Create and manage subscription plans, pricing, and features',
                    'route'       => 'admin.subscription.plans.index',
                    'permission'  => 'subscription-list',
                    'icon'        => 'layer',
                    'color'       => 'primary',
                    'badge'       => 'Subscriptions',
                    'keywords'    => ['subscription', 'plans', 'billing', 'pricing'],
                ],
                'user_subscriptions' => [
                    'label'       => 'User Subscriptions',
                    'description' => 'View and manage all active and historical user subscriptions',
                    'route'       => 'admin.subscription.user-subscriptions.index',
                    'permission'  => 'subscription-list',
                    'icon'        => 'people',
                    'color'       => 'info',
                    'badge'       => 'Subscriptions',
                    'keywords'    => ['subscribers', 'subscriptions', 'members'],
                ],
            ],
        ],
        'communication_support' => [
            'label'       => 'Communication & Support',
            'description' => 'Reach users quickly and manage support workflows efficiently',
            'icon'        => 'notification',
            'color'       => 'info',
            'items'       => [
                'notify_users' => [
                    'label'       => 'Notify Users',
                    'description' => 'Send direct updates, alerts, and important announcements',
                    'route'       => 'admin.notifications.notifyToUser',
                    'permission'  => 'custom-notify-users',
                    'icon'        => 'send-mail',
                    'color'       => 'primary',
                    'badge'       => 'Alerts',
                    'keywords'    => ['mail', 'announcement', 'notifications'],
                ],
                'notification_center' => [
                    'label'       => 'Notification Center',
                    'description' => 'Manage notification records and delivery activity',
                    'route'       => 'admin.notifications.index',
                    'permission'  => 'notification-list',
                    'icon'        => 'notification',
                    'color'       => 'info',
                    'badge'       => 'Alerts',
                    'keywords'    => ['notifications', 'records', 'history'],
                ],
                'notification_templates' => [
                    'label'       => 'Notification Templates',
                    'description' => 'Maintain reusable messaging templates and channel content',
                    'route'       => 'admin.notifications.template.index',
                    'permission'  => 'notification-template-list',
                    'icon'        => 'template',
                    'color'       => 'secondary',
                    'badge'       => 'Alerts',
                    'keywords'    => ['templates', 'email', 'sms'],
                ],
                'support_tickets' => [
                    'label'       => 'Support Tickets',
                    'description' => 'Review customer tickets, replies, and support backlog',
                    'route'       => 'admin.support-ticket.history',
                    'permission'  => 'support-ticket-list',
                    'icon'        => 'support-ticket',
                    'color'       => 'warning',
                    'badge'       => 'Support',
                    'keywords'    => ['tickets', 'customer care', 'support'],
                ],
                'support_categories' => [
                    'label'       => 'Support Categories',
                    'description' => 'Organize support request types and service grouping',
                    'route'       => 'admin.support-ticket.category.index',
                    'permission'  => 'support-ticket-category-manage',
                    'icon'        => 'tags',
                    'color'       => 'secondary',
                    'badge'       => 'Support',
                    'keywords'    => ['categories', 'support', 'ticket types'],
                ],
                'subscribers' => [
                    'label'       => 'Subscribers',
                    'description' => 'Manage newsletter contacts and subscriber growth',
                    'route'       => 'admin.subscriber.index',
                    'permission'  => 'subscriber-list',
                    'icon'        => 'subscriber',
                    'color'       => 'success',
                    'badge'       => 'Audience',
                    'keywords'    => ['newsletter', 'mailing', 'subscribers'],
                ],
            ],
        ],
        'site_content' => [
            'label'       => 'Site Content',
            'description' => 'Manage public-facing pages, navigation, and SEO essentials',
            'icon'        => 'site-essentials',
            'color'       => 'primary',
            'items'       => [
                'landing_pages' => [
                    'label'       => 'Landing Pages',
                    'description' => 'Create and manage custom landing page experiences',
                    'route'       => 'admin.custom-landing.index',
                    'permission'  => 'custom-landing-list',
                    'icon'        => 'custom-landing',
                    'color'       => 'primary',
                    'badge'       => 'CMS',
                    'keywords'    => ['landing', 'pages', 'marketing'],
                ],
                'navigation' => [
                    'label'       => 'Navigation',
                    'description' => 'Maintain site menus and public navigation structure',
                    'route'       => 'admin.navigation.site.index',
                    'permission'  => 'navigation-manage',
                    'icon'        => 'navigation',
                    'color'       => 'info',
                    'badge'       => 'CMS',
                    'keywords'    => ['menus', 'navigation', 'header'],
                ],
                'site_pages' => [
                    'label'       => 'Site Pages',
                    'description' => 'Manage pages, sections, and reusable page content',
                    'route'       => 'admin.page.site.index',
                    'permission'  => 'page-list',
                    'icon'        => 'page',
                    'color'       => 'secondary',
                    'badge'       => 'CMS',
                    'keywords'    => ['pages', 'content', 'builder'],
                ],
                'blog_posts' => [
                    'label'       => 'Blog Posts',
                    'description' => 'Publish blog content and manage editorial activity',
                    'route'       => 'admin.blog.post.index',
                    'permission'  => 'blog-list',
                    'icon'        => 'blog',
                    'color'       => 'success',
                    'badge'       => 'CMS',
                    'keywords'    => ['blog', 'articles', 'content'],
                ],
                'seo_settings' => [
                    'label'       => 'SEO Settings',
                    'description' => 'Control search visibility and optimization settings',
                    'route'       => 'admin.site-seo.index',
                    'permission'  => 'seo-manage',
                    'icon'        => 'seo',
                    'color'       => 'warning',
                    'badge'       => 'CMS',
                    'keywords'    => ['seo', 'meta', 'search'],
                ],
            ],
        ],
        'platform_configuration' => [
            'label'       => 'Platform Configuration',
            'description' => 'Manage settings, localization, roles, staff, and tools',
            'icon'        => 'setting-1',
            'color'       => 'secondary',
            'items'       => [
                'site_settings' => [
                    'label'       => 'Site Settings',
                    'description' => 'Configure platform-wide settings and business preferences',
                    'route'       => 'admin.settings.site.index',
                    'permission'  => 'site-setting-view',
                    'icon'        => 'site-setting',
                    'color'       => 'secondary',
                    'badge'       => 'System',
                    'keywords'    => ['settings', 'configuration', 'platform'],
                ],
                'plugins' => [
                    'label'       => 'Plugins',
                    'description' => 'Enable and manage available plugin integrations',
                    'route'       => 'admin.settings.plugin.index',
                    'permission'  => 'plugins-manage',
                    'icon'        => 'plugins',
                    'color'       => 'primary',
                    'badge'       => 'System',
                    'keywords'    => ['plugins', 'extensions', 'integration'],
                ],
                'languages' => [
                    'label'       => 'Languages',
                    'description' => 'Manage translations and language availability',
                    'route'       => 'admin.language.index',
                    'permission'  => 'language-list',
                    'icon'        => 'language',
                    'color'       => 'info',
                    'badge'       => 'System',
                    'keywords'    => ['language', 'translation', 'localization'],
                ],
                'roles_permissions' => [
                    'label'       => 'Roles & Permissions',
                    'description' => 'Control admin access rules and permission assignments',
                    'route'       => 'admin.role.index',
                    'permission'  => 'role-list',
                    'icon'        => 'role-management',
                    'color'       => 'danger',
                    'badge'       => 'Access',
                    'keywords'    => ['roles', 'permissions', 'access control'],
                ],
                'staff' => [
                    'label'       => 'Staff',
                    'description' => 'Manage internal admin users and staff members',
                    'route'       => 'admin.staff.index',
                    'permission'  => 'staff-list',
                    'icon'        => 'staff-management',
                    'color'       => 'success',
                    'badge'       => 'Access',
                    'keywords'    => ['staff', 'admin users', 'team'],
                ],
                'style_manager' => [
                    'label'       => 'Style Manager',
                    'description' => 'Customize backend styling and visual design adjustments',
                    'route'       => 'admin.app.style-manager',
                    'permission'  => 'style-manager',
                    'icon'        => 'app-style-code',
                    'color'       => 'warning',
                    'badge'       => 'Tools',
                    'keywords'    => ['css', 'styles', 'appearance'],
                ],
                'app_info' => [
                    'label'       => 'App Info',
                    'description' => 'Review environment, server, and application information',
                    'route'       => 'admin.app.info',
                    'permission'  => 'app-info',
                    'icon'        => 'app',
                    'color'       => 'secondary',
                    'badge'       => 'Tools',
                    'keywords'    => ['system info', 'environment', 'application'],
                ],
            ],
        ],
    ],
];
