<?php

use App\Support\NotificationTuneLibrary;

return [
    'signup_bonus_settings' => [
        'title'              => 'Signup Bonus Settings',
        'menu_label'         => 'Signup Bonus',
        'menu_description'   => 'Reward new accounts',
        'header_description' => 'Credit new users with a welcome bonus on registration. Bonus amount can vary per role and can be gated behind email verification.',
        'icon'               => 'sidebar-rocket',
        'groups'             => [
            [
                'title'       => 'Program Availability',
                'description' => 'Master toggle for the signup bonus and whether email verification is required before crediting.',
                'fields'      => ['signup_bonus_enabled', 'signup_bonus_require_email_verified'],
            ],
            [
                'title'       => 'Bonus Amount per Role',
                'description' => 'Amount credited to the user\'s default wallet in the site default currency. Set to 0 to disable for that role.',
                'fields'      => ['signup_bonus_user_amount', 'signup_bonus_merchant_amount', 'signup_bonus_agent_amount'],
            ],
        ],

        'elements' => [
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'signup_bonus_enabled',
                'label'   => 'Enable Signup Bonus',
                'rules'   => 'required|boolean',
                'value'   => 0,
                'class'   => 'col-md-6',
                'message' => 'Master switch. When off, new accounts will not receive any signup bonus.',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'signup_bonus_require_email_verified',
                'label'   => 'Require Email Verification',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-6',
                'message' => 'When on, the bonus is credited after the user verifies their email. When off, the bonus is credited immediately on registration.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'string',
                'key'     => 'signup_bonus_user_amount',
                'label'   => 'User Bonus Amount',
                'unit'    => 'USD',
                'rules'   => 'required|numeric|min:0',
                'value'   => '0',
                'class'   => 'col-md-4',
                'message' => 'Amount credited to standard user accounts in the site default currency.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'string',
                'key'     => 'signup_bonus_merchant_amount',
                'label'   => 'Merchant Bonus Amount',
                'unit'    => 'USD',
                'rules'   => 'required|numeric|min:0',
                'value'   => '0',
                'class'   => 'col-md-4',
                'message' => 'Amount credited to merchant accounts in the site default currency.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'string',
                'key'     => 'signup_bonus_agent_amount',
                'label'   => 'Agent Bonus Amount',
                'unit'    => 'USD',
                'rules'   => 'required|numeric|min:0',
                'value'   => '0',
                'class'   => 'col-md-4',
                'message' => 'Amount credited to agent accounts in the site default currency.',
            ],
        ],
    ],

    'general_settings' => [
        'title'              => 'General Settings',
        'menu_label'         => 'General',
        'menu_description'   => 'Brand, routing, support',
        'header_description' => 'Manage brand identity, routes, currency precision, and support details.',
        'icon'               => 'cil-equalizer',
        'groups'             => [
            [
                'title'       => 'Site Identity',
                'description' => 'Core site naming, currency precision, and default loading behavior.',
                'fields'      => ['site_title', 'site_decimal', 'preloader_text'],
            ],
            [
                'title'       => 'Access & Routing',
                'description' => 'Admin URL prefix, timezone, and first destination after landing.',
                'fields'      => ['admin_prefix', 'site_timezone', 'home_redirect'],
            ],
            [
                'title'       => 'Brand Assets',
                'description' => 'Logos, favicon, login artwork, and breadcrumb image used across the product.',
                'fields'      => ['logo', 'light_logo', 'small_logo', 'site_favicon', 'login_banner', 'default_breadcrumb_image'],
            ],
            [
                'title'       => 'Support & Footer',
                'description' => 'Public support contact details and footer ownership text.',
                'fields'      => ['support_email', 'support_phone', 'copyright_text'],
            ],
        ],

        'elements' => [
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'logo',
                'label' => 'Logo',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:1000',
                'value' => 'general/static/logo/digikash-mark.svg',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'light_logo',
                'label' => 'Light Logo',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:1000',
                'value' => 'general/static/logo/digikash-mark.svg',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'small_logo',
                'label' => 'Small Logo',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:1000',
                'value' => 'general/static/logo/digikash-mark.svg',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'site_favicon',
                'label' => 'Site Favicon',
                'rules' => 'mimes:jpeg,jpg,png,ico,svg|max:1000',
                'value' => 'general/static/logo/digikash-mark.svg',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'login_banner',
                'label' => 'Login Banner',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:2000',
                'value' => 'img/welcome-vector.png',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'default_breadcrumb_image',
                'label' => 'Default Breadcrumb Image',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:2000',
                'value' => 'img/welcome-vector.png',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'site_title',
                'label' => 'Site Title',
                'rules' => 'required|min:2|max:500',
                'value' => 'Coevs',
                'class' => 'col-md-6',
            ],
            [
                'type'    => 'select',
                'data'    => 'integer',
                'key'     => 'site_decimal',
                'label'   => 'Currency Decimal Places',
                'rules'   => 'required|integer|min:0|max:8',
                'value'   => 2,
                'class'   => 'col-md-6',
                'message' => 'Number of digits after decimal point to format all monetary values across the site.',
            ],
            [
                'type'  => 'hidden',
                'data'  => 'bool',
                'key'   => 'site_preloader',
                'rules' => 'required|boolean',
                'value' => 0,
            ],
            [
                'type'          => 'group_text',
                'data'          => 'string',
                'key'           => 'preloader_text',
                'label'         => 'Site Preloader',
                'related_field' => 'site_preloader',
                'rules'         => 'required',
                'value'         => 'Loading',
                'class'         => 'col-md-12',
                'message'       => 'Enter text to be displayed on the preloader, separated by commas.',
            ],
            [
                'type'    => 'text',
                'data'    => 'string',
                'key'     => 'admin_prefix',
                'label'   => 'Admin Prefix',
                'rules'   => 'required|max:10',
                'value'   => 'admin',
                'class'   => 'col-md-4',
                'message' => 'Prefix for admin panel routes. When you change this, you need to Re login with the new prefix for it to take effect.',
            ],
            [
                'type'  => 'select',
                'data'  => 'string',
                'key'   => 'site_timezone',
                'label' => 'Site Timezone',
                'rules' => 'required',
                'value' => [],
                'class' => 'col-md-4',
            ],
            [
                'type'    => 'select',
                'data'    => 'string',
                'key'     => 'home_redirect',
                'label'   => 'Home Redirect',
                'rules'   => 'required',
                'value'   => [],
                'class'   => 'col-md-4',
                'message' => 'All Page Slugs',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'support_email',
                'label' => 'Support Email',
                'rules' => 'required|min:4|max:199',
                'value' => 'support@demo.com',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'support_phone',
                'label' => 'Support Phone',
                'rules' => 'required|min:4|max:199',
                'value' => '+1234567890',
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'copyright_text',
                'label' => 'Copyright Text',
                'rules' => 'required|min:4|max:199',
                'value' => 'admin',
                'class' => 'col-md-4',
            ],

        ],
    ],

    'role_branding_settings' => [
        'title'              => 'Role Branding Settings',
        'menu_label'         => 'Role Branding',
        'menu_description'   => 'Role colors and accents',
        'header_description' => 'Choose the primary and accent colors used for user, merchant, and agent experiences.',
        'icon'               => 'sidebar-palette',
        'groups'             => [
            [
                'title'       => 'User Theme',
                'description' => 'Controls the default customer dashboard and auth color system.',
                'fields'      => ['user_role_primary_color', 'user_role_accent_color'],
            ],
            [
                'title'       => 'Merchant Theme',
                'description' => 'Controls merchant-facing success and business profile accents.',
                'fields'      => ['merchant_role_primary_color', 'merchant_role_accent_color'],
            ],
            [
                'title'       => 'Agent Theme',
                'description' => 'Controls the agent module palette, gradients, and soft surfaces.',
                'fields'      => ['agent_role_primary_color', 'agent_role_accent_color'],
            ],
        ],
        'elements' => [
            [
                'type'    => 'color',
                'data'    => 'string',
                'key'     => 'user_role_primary_color',
                'label'   => 'User Primary Color',
                'rules'   => 'required|regex:/^#[0-9A-Fa-f]{6}$/',
                'value'   => '#4663ee',
                'class'   => 'col-md-6',
                'message' => 'Main customer-facing action color used in auth and dashboard screens.',
            ],
            [
                'type'    => 'color',
                'data'    => 'string',
                'key'     => 'user_role_accent_color',
                'label'   => 'User Accent Color',
                'rules'   => 'required|regex:/^#[0-9A-Fa-f]{6}$/',
                'value'   => '#17a86a',
                'class'   => 'col-md-6',
                'message' => 'Secondary customer-facing highlight color.',
            ],
            [
                'type'    => 'color',
                'data'    => 'string',
                'key'     => 'merchant_role_primary_color',
                'label'   => 'Merchant Primary Color',
                'rules'   => 'required|regex:/^#[0-9A-Fa-f]{6}$/',
                'value'   => '#16a34a',
                'class'   => 'col-md-6',
                'message' => 'Business and merchant success color used for commercial workflows.',
            ],
            [
                'type'    => 'color',
                'data'    => 'string',
                'key'     => 'merchant_role_accent_color',
                'label'   => 'Merchant Accent Color',
                'rules'   => 'required|regex:/^#[0-9A-Fa-f]{6}$/',
                'value'   => '#14b8a6',
                'class'   => 'col-md-6',
                'message' => 'Secondary merchant highlight color.',
            ],
            [
                'type'    => 'color',
                'data'    => 'string',
                'key'     => 'agent_role_primary_color',
                'label'   => 'Agent Primary Color',
                'rules'   => 'required|regex:/^#[0-9A-Fa-f]{6}$/',
                'value'   => '#4f46e5',
                'class'   => 'col-md-6',
                'message' => 'Main agent module color for agent dashboards, badges, and buttons.',
            ],
            [
                'type'    => 'color',
                'data'    => 'string',
                'key'     => 'agent_role_accent_color',
                'label'   => 'Agent Accent Color',
                'rules'   => 'required|regex:/^#[0-9A-Fa-f]{6}$/',
                'value'   => '#f59e0b',
                'class'   => 'col-md-6',
                'message' => 'Secondary agent highlight color used for gradients and warm accents.',
            ],
        ],
    ],

    'site_security' => [
        'title'              => 'Security Settings',
        'menu_label'         => 'Security',
        'menu_description'   => 'Locks, HTTPS, uploads',
        'header_description' => 'Tune transport, session, upload, and duplicate submission safeguards.',
        'icon'               => 'security',
        'groups'             => [
            [
                'title'       => 'Access Protection',
                'description' => 'Transport security and automatic session lock controls.',
                'fields'      => ['force_https', 'screen_lock_time'],
            ],
            [
                'title'       => 'Authentication Lockouts',
                'description' => 'Brute-force protection for user, merchant, agent, and admin sign-in attempts.',
                'fields'      => ['login_attempt_limit', 'login_lock_minutes'],
            ],
            [
                'title'       => 'Browser Protection',
                'description' => 'Response headers that reduce clickjacking, MIME sniffing, referrer leakage, and browser permission abuse.',
                'fields'      => ['secure_response_headers', 'strict_transport_security'],
            ],
            [
                'title'       => 'Wallet Payment Protection',
                'description' => 'Wallet PIN brute-force controls used by merchant checkout and payment links.',
                'fields'      => ['wallet_pin_attempt_limit', 'wallet_pin_lock_minutes'],
            ],
            [
                'title'       => 'Merchant API Protection',
                'description' => 'Signature, replay-window, and abuse controls for merchant payment API requests.',
                'fields'      => ['merchant_api_signature_required', 'merchant_api_timestamp_tolerance', 'merchant_api_rate_limit_per_minute'],
            ],
            [
                'title'       => 'Request & Upload Limits',
                'description' => 'Submission throttling and file upload limits for safer operations.',
                'fields'      => ['submission_lock_duration', 'max_upload_size'],
            ],
        ],
        'elements' => [
            [
                'type'  => 'switch',
                'data'  => 'bool',
                'key'   => 'force_https',
                'label' => 'Force HTTPS',
                'rules' => 'required|boolean',
                'value' => 0,
                'class' => 'col-md-4',
            ],
            [
                'type'  => 'hidden',
                'data'  => 'bool',
                'key'   => 'screen_lock',
                'rules' => 'required|boolean',
                'value' => 0,
            ],
            [
                'type'          => 'group_text',
                'data'          => 'integer',
                'key'           => 'screen_lock_time',
                'label'         => 'Screen Lock',
                'unit'          => 'minutes',
                'related_field' => 'screen_lock',
                'rules'         => 'required|integer',
                'value'         => 5,
                'class'         => 'col-md-8',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'integer',
                'key'     => 'login_attempt_limit',
                'label'   => 'Login Attempt Limit',
                'unit'    => 'attempts',
                'rules'   => 'required|integer|min:3|max:10',
                'value'   => 5,
                'class'   => 'col-md-6',
                'message' => 'Maximum failed login attempts before sign-in is temporarily locked for the same account and IP.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'integer',
                'key'     => 'login_lock_minutes',
                'label'   => 'Login Lock Duration',
                'unit'    => 'minutes',
                'rules'   => 'required|integer|min:1|max:60',
                'value'   => 15,
                'class'   => 'col-md-6',
                'message' => 'How long sign-in stays locked after repeated failed attempts. Recommended value: 15 minutes.',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'secure_response_headers',
                'label'   => 'Secure Response Headers',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-6',
                'message' => 'Adds anti-clickjacking, MIME sniffing, referrer, cross-origin, and permissions-policy headers to every response.',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'strict_transport_security',
                'label'   => 'Strict Transport Security',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-6',
                'message' => 'Sends HSTS so modern browsers keep using HTTPS after the first secure visit. Keep Force HTTPS enabled in production.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'integer',
                'key'     => 'wallet_pin_attempt_limit',
                'label'   => 'Wallet PIN Attempt Limit',
                'unit'    => 'attempts',
                'rules'   => 'required|integer|min:3|max:10',
                'value'   => 5,
                'class'   => 'col-md-6',
                'message' => 'Maximum failed Wallet PIN attempts before payment authorization is locked. Recommended value: 5.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'integer',
                'key'     => 'wallet_pin_lock_minutes',
                'label'   => 'Wallet PIN Lock Duration',
                'unit'    => 'minutes',
                'rules'   => 'required|integer|min:1|max:60',
                'value'   => 15,
                'class'   => 'col-md-6',
                'message' => 'Lockout duration after repeated failed Wallet PIN attempts. Recommended value: 15 minutes.',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'merchant_api_signature_required',
                'label'   => 'Require Merchant API Signatures',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-4',
                'message' => 'Requires every merchant API request to include a valid HMAC-SHA256 X-Signature header.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'integer',
                'key'     => 'merchant_api_timestamp_tolerance',
                'label'   => 'API Timestamp Tolerance',
                'unit'    => 'seconds',
                'rules'   => 'required|integer|min:60|max:900',
                'value'   => 300,
                'class'   => 'col-md-4',
                'message' => 'Rejects signed merchant API requests outside this timestamp window to reduce replay attacks.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'integer',
                'key'     => 'merchant_api_rate_limit_per_minute',
                'label'   => 'Merchant API Rate Limit',
                'unit'    => 'requests/min',
                'rules'   => 'required|integer|min:30|max:600',
                'value'   => 120,
                'class'   => 'col-md-4',
                'message' => 'Per-merchant and per-IP API request cap for payment initiation, verification, and site-info calls.',
            ],
            [
                'type'  => 'group_text',
                'data'  => 'integer',
                'key'   => 'submission_lock_duration',
                'label' => 'Duplicate Submission Lock Duration',
                'unit'  => 'seconds',
                'info'  => 'Recommended value: 5',
                'rules' => 'required|integer',
                'value' => 5,
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'group_text',
                'data'  => 'integer',
                'key'   => 'max_upload_size',
                'label' => 'Max Upload Size',
                'unit'  => 'MB',
                'rules' => 'required|integer|min:1',
                'value' => 5,
                'class' => 'col-md-6',
            ],
        ],
    ],
    'maintenance_mode' => [
        'title'              => 'Maintenance Mode Settings',
        'menu_label'         => 'Maintenance',
        'menu_description'   => 'Downtime screen, recovery',
        'header_description' => 'Prepare downtime access, recovery key, and the maintenance screen.',
        'info'               => 'Caution: Enabling Maintenance Mode requires remembering the Secret Key to restore the website.',
        'info_icon'          => 'fa fa-exclamation-triangle text-warning',
        'icon'               => 'cil-memory',
        'groups'             => [
            [
                'title'       => 'Access Recovery',
                'description' => 'Keep the secret key ready before enabling the public maintenance screen.',
                'fields'      => ['secret_key', 'maintenance_mode'],
            ],
            [
                'title'       => 'Runtime Controls',
                'description' => 'Operational controls for the site environment and development mode.',
                'fields'      => ['site_environment', 'development_mode'],
            ],
            [
                'title'       => 'Maintenance Screen',
                'description' => 'The visual cover and copy shown while the site is unavailable.',
                'fields'      => ['maintenance_cover', 'maintenance_title', 'maintenance_text'],
            ],
        ],
        'elements' => [
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'maintenance_cover',
                'label' => 'Cover Image',
                'rules' => 'mimes:jpeg,jpg,png,svg|max:2000',
                'value' => '',
                'class' => 'col-md-6',
            ],
            [
                'type'     => 'text',
                'data'     => 'string',
                'key'      => 'secret_key',
                'label'    => 'Secret Key',
                'rules'    => 'required',
                'value'    => 'secret',
                'class'    => 'col-md-6',
                'message'  => 'Remember the secret key: domain/secret-key. Utilize it to restore the website live.',
                'copyable' => true,
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'maintenance_title',
                'label' => 'Title',
                'rules' => 'required',
                'value' => 'Site is not under maintenance',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'textarea',
                'data'  => 'string',
                'key'   => 'maintenance_text',
                'label' => 'Maintenance Text',
                'rules' => 'required|max:500',
                'value' => 'Sorry for interrupt! Site will live soon.',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'select',
                'data'  => 'string',
                'key'   => 'site_environment',
                'label' => 'Site Environment',
                'rules' => 'required',
                'value' => [],
                'class' => 'col-md-6',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'development_mode',
                'label'   => 'Development Mode',
                'rules'   => 'boolean',
                'value'   => true,
                'class'   => 'col-md-6',
                'message' => 'Enable this feature only when debug or script changes are required',
            ],
            [
                'type'                   => 'switch',
                'data'                   => 'bool',
                'key'                    => 'maintenance_mode',
                'label'                  => 'Maintenance Mode',
                'rules'                  => 'boolean',
                'value'                  => 1,
                'class'                  => 'col-md-6',
                'message'                => 'Only activate it after saving and remembering the Secret Key.',
                'enable_warning'         => 'Before enabling Maintenance Mode, copy and remember the Secret Key. Without it, the client may not be able to access the site or restore it later.',
                'enable_warning_title'   => 'Enable Maintenance Mode?',
                'enable_warning_confirm' => 'Yes, Enable Maintenance',
            ],
        ],
    ],
    'mail_settings' => [
        'title'              => 'SMTP Mail Settings',
        'menu_label'         => 'Email',
        'menu_description'   => 'SMTP sender and transport',
        'header_description' => 'Configure sender identity, SMTP credentials, and connection testing.',
        'info'               => 'When using Gmail SMTP, your custom "From Address" may be replaced automatically by your authenticated Gmail address due to security policies.
                    To send emails with a custom address (like support@yourdomain.com), use a verified SMTP provider such as Mailgun, Amazon SES, or your domain\'s SMTP server with proper SPF, DKIM, and DMARC setup.
                    A connection test will send a verification email to confirm your settings.',
        'icon'             => 'cil-send',
        'include_partials' => '_smtp_test',
        'groups'           => [
            [
                'title'       => 'Sender Identity',
                'description' => 'Display name and from-address used for outbound emails.',
                'fields'      => ['email_from_name', 'email_from_address'],
            ],
            [
                'title'       => 'SMTP Authentication',
                'description' => 'Credentials used to authenticate with your mail provider.',
                'fields'      => ['mail_username', 'mail_password'],
            ],
            [
                'title'       => 'Connection Settings',
                'description' => 'Host, port, and encryption protocol for the SMTP transport.',
                'fields'      => ['mail_host', 'mail_port', 'mail_secure'],
            ],
        ],
        'elements' => [
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'email_from_name',
                'label' => 'Email From Name',
                'rules' => 'required|max:50',
                'value' => 'Coevs',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'email_from_address',
                'label' => 'Email From Address',
                'rules' => 'required|min:5|max:50',
                'value' => 'coevs@gmail.com',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'mail_username',
                'label' => 'Mail Username',
                'rules' => 'required',
                'value' => 'test',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'mail_password',
                'label' => 'Mail Password',
                'rules' => 'required',
                'value' => '0000',
                'class' => 'col-md-6',
            ],

            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'mail_host',
                'label' => 'Mail Host',
                'rules' => 'required',
                'value' => 'mail.coevs.co',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'text',
                'data'  => 'integer',
                'key'   => 'mail_port',
                'label' => 'Mail Port',
                'rules' => 'required',
                'value' => '465',
                'class' => 'col-md-3',
            ],
            [
                'type'  => 'select',
                'data'  => 'string',
                'key'   => 'mail_secure',
                'label' => 'Encryption',
                'rules' => 'required',
                'value' => [],
                'class' => 'col-md-3',
            ],
        ],
    ],
    'cookie_settings' => [
        'title'              => 'Cookie Settings',
        'menu_label'         => 'Cookies',
        'menu_description'   => 'Consent notice content',
        'header_description' => 'Edit the customer consent notice, summary copy, URL, and visibility.',
        'icon'               => 'cil-bug',
        'groups'             => [
            [
                'title'       => 'Consent Content',
                'description' => 'Text and destination shown in the customer cookie notice.',
                'fields'      => ['cookie_title', 'cookie_url', 'cookie_summary'],
            ],
            [
                'title'       => 'Consent Status',
                'description' => 'Control whether the cookie notice is visible to customers.',
                'fields'      => ['cookie_status'],
            ],
        ],
        'elements' => [
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'cookie_title',
                'label' => 'Cookie Title',
                'rules' => 'required',
                'value' => 'Cookies Consent',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'textarea',
                'data'  => 'string',
                'key'   => 'cookie_summary',
                'label' => 'Cookie Summary',
                'rules' => 'required',
                'value' => 'This website use cookies to help you have a superior and more relevant browsing experience on the website.',
                'class' => 'col-md-12',
            ],
            [
                'type'  => 'text',
                'data'  => 'string',
                'key'   => 'cookie_url',
                'label' => 'Cookie Page Url',
                'rules' => 'required',
                'value' => '/',
                'class' => 'col-md-6',
            ],
            [
                'type'  => 'switch',
                'data'  => 'bool',
                'key'   => 'cookie_status',
                'label' => 'Enable Cookie',
                'rules' => 'boolean',
                'value' => true,
                'class' => 'col-md-6',
            ],
        ],
    ],
    'notification_settings' => [
        'title'              => 'Notification Sound Settings',
        'menu_label'         => 'Notifications',
        'menu_description'   => 'Sounds and delivery',
        'header_description' => 'Set the platform default notification behavior and sound preference.',
        'icon'               => 'notification',
        'include_partials'   => '_notification_tune_preview',
        'groups'             => [
            [
                'title'       => 'Delivery Defaults',
                'description' => 'Defaults used until a user or admin saves their own preference.',
                'fields'      => ['notification_delivery_enabled', 'notification_tune_sound_enabled'],
            ],
            [
                'title'       => 'Default Sound',
                'description' => 'The tune used for real-time in-app notifications by default.',
                'fields'      => ['notification_tune_default'],
            ],
        ],
        'elements' => [
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'notification_delivery_enabled',
                'label'   => 'Enable In-App Notifications',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-6',
                'message' => 'When disabled, in-app database and broadcast notifications are off by default. Email and SMS templates are not affected.',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'notification_tune_sound_enabled',
                'label'   => 'Play Notification Tune',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-6',
                'message' => 'When disabled, users and admins start with notification sounds muted unless they save their own preference.',
            ],
            [
                'type'    => 'select',
                'data'    => 'string',
                'key'     => 'notification_tune_default',
                'label'   => 'Default Notification Tune',
                'rules'   => 'required|in:'.implode(',', NotificationTuneLibrary::keys()),
                'value'   => NotificationTuneLibrary::DEFAULT_KEY,
                'class'   => 'col-md-6',
                'message' => 'Preview the selected tune from this settings header before saving.',
            ],
        ],
    ],
    'agent_settings' => [
        'title'              => 'Agent Program Settings',
        'menu_label'         => 'Agents',
        'menu_description'   => 'Onboarding and commission',
        'header_description' => 'Control agent onboarding, approvals, commission limits, and notifications.',
        'icon'               => 'sidebar-agent',
        'info'               => 'Control how the Agent program works on this platform - toggle the program globally, gate registrations, fine-tune commission rules, and decide which countries can apply.',
        'groups'             => [
            [
                'title'       => 'Program Availability',
                'description' => 'Global agent visibility, public signup, and automatic approval behavior.',
                'fields'      => ['agent_program_enabled', 'agent_self_registration', 'agent_auto_approve'],
            ],
            [
                'title'       => 'Review Requirements',
                'description' => 'Application gatekeeping, profile limits, and generated agent code rules.',
                'fields'      => ['agent_require_kyc', 'agent_max_per_user', 'agent_code_prefix'],
            ],
            [
                'title'       => 'Commission Rules',
                'description' => 'Default commission and bounds enforced when agents are managed.',
                'fields'      => ['agent_default_commission', 'agent_min_commission', 'agent_max_commission'],
            ],
            [
                'title'       => 'Country Eligibility',
                'description' => 'Optional ISO-2 country allowlist for who can submit an application.',
                'fields'      => ['agent_allowed_countries'],
            ],
            [
                'title'       => 'Notifications',
                'description' => 'Email notifications for admins and users across application changes.',
                'fields'      => ['agent_admin_email_notify', 'agent_user_email_notify'],
            ],
        ],
        'elements' => [
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'agent_program_enabled',
                'label'   => 'Enable Agent Program',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-4',
                'message' => 'Master switch. When off, every agent surface is hidden and routes return 404.',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'agent_self_registration',
                'label'   => 'Allow Public Registration',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-4',
                'message' => 'When enabled, anyone can sign up at /agent/register. When disabled, only admin-converted users can become agents.',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'agent_auto_approve',
                'label'   => 'Auto-Approve New Agents',
                'rules'   => 'required|boolean',
                'value'   => 0,
                'class'   => 'col-md-4',
                'message' => 'When enabled, new agent applications skip the admin review queue and are activated immediately.',
            ],
            [
                'type'        => 'switch',
                'data'        => 'bool',
                'key'         => 'agent_require_kyc',
                'label'       => 'Require KYC',
                'rules'       => 'required|boolean',
                'value'       => 0,
                'class'       => 'col-md-4',
                'description' => 'Require verified KYC before agent approval.',
                'message'     => 'When enabled, the user must have an approved KYC submission before they can apply to become an agent.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'integer',
                'key'     => 'agent_max_per_user',
                'label'   => 'Max Agent Profiles Per User',
                'unit'    => 'profiles',
                'rules'   => 'required|integer|min:1|max:50',
                'value'   => 1,
                'class'   => 'col-md-4',
                'message' => 'Hard cap on how many agent profiles a single user account can own.',
            ],
            [
                'type'    => 'text',
                'data'    => 'string',
                'key'     => 'agent_code_prefix',
                'label'   => 'Agent Code Prefix',
                'rules'   => 'required|string|max:8',
                'value'   => 'AGT-',
                'class'   => 'col-md-4',
                'message' => 'Prefix prepended to every auto-generated agent code.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'string',
                'key'     => 'agent_default_commission',
                'label'   => 'Default Commission',
                'unit'    => '%',
                'rules'   => 'required|numeric|min:0|max:100',
                'value'   => '0',
                'class'   => 'col-md-4',
                'message' => 'Commission percentage applied to a new agent profile when it is created.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'string',
                'key'     => 'agent_min_commission',
                'label'   => 'Minimum Commission',
                'unit'    => '%',
                'rules'   => 'required|numeric|min:0|max:100',
                'value'   => '0',
                'class'   => 'col-md-4',
                'message' => 'Lower bound enforced when admin sets the commission for an individual agent.',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'string',
                'key'     => 'agent_max_commission',
                'label'   => 'Maximum Commission',
                'unit'    => '%',
                'rules'   => 'required|numeric|min:0|max:100',
                'value'   => '100',
                'class'   => 'col-md-4',
                'message' => 'Upper bound enforced when admin sets the commission for an individual agent.',
            ],
            [
                'type'    => 'textarea',
                'data'    => 'string',
                'key'     => 'agent_allowed_countries',
                'label'   => 'Allowed Countries',
                'rules'   => 'nullable|string|max:1000',
                'value'   => '',
                'class'   => 'col-md-12',
                'message' => 'Comma-separated ISO-2 country codes (e.g. BD,IN,PK). Leave empty to allow every country.',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'agent_admin_email_notify',
                'label'   => 'Notify Admin On New Request',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-6',
                'message' => 'When enabled, admins are emailed every time a user submits an agent application.',
            ],
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'agent_user_email_notify',
                'label'   => 'Notify User On Status Change',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-6',
                'message' => 'When enabled, users are emailed when their agent application status changes.',
            ],
        ],
    ],
    'pwa_settings' => [
        'title'              => 'Mobile App (PWA) Settings',
        'menu_label'         => 'Mobile App',
        'menu_description'   => 'Installable PWA for dashboards',
        'header_description' => 'Configure the installable mobile app shell shown to user, merchant, and agent dashboards.',
        'icon'               => 'cil-mobile',
        'info'               => 'IMPORTANT: PWA install only works over HTTPS (or http://localhost on the same machine). On a real mobile device opening the site over http:// the install button will do nothing and "Add to Home Screen" will open in a normal browser tab. To enable PWA on mobile: (1) serve the site over HTTPS (Laravel Herd users: right-click the site in Herd and choose Secure), (2) make sure APP_URL in .env starts with https://, (3) clear browser data on the mobile device, then reload. After changing icons or theme, users may need to remove and reinstall the app to see the change.',
        'info_icon'          => 'fa fa-exclamation-triangle text-warning',
        'groups'             => [
            [
                'title'       => 'Availability',
                'description' => 'Master toggle for the installable mobile app shell.',
                'fields'      => ['pwa_enabled'],
            ],
            [
                'title'       => 'Identity',
                'description' => 'How the app appears on the home screen and inside the install dialog.',
                'fields'      => ['pwa_app_name', 'pwa_short_name', 'pwa_description'],
            ],
            [
                'title'       => 'Appearance',
                'description' => 'Theme colors, display mode, and orientation used by the installed app.',
                'fields'      => ['pwa_theme_color', 'pwa_background_color', 'pwa_display', 'pwa_orientation'],
            ],
            [
                'title'       => 'Icons',
                'description' => 'Square PNG icons shown on the home screen, install dialog, and inside the app.',
                'fields'      => ['pwa_icon_192', 'pwa_icon_512', 'pwa_maskable_icon', 'pwa_apple_touch_icon'],
            ],
            [
                'title'       => 'Offline Experience',
                'description' => 'Copy and behavior shown when the user goes offline. Bump cache version to force installed apps to refresh assets.',
                'fields'      => ['pwa_offline_message', 'pwa_cache_version'],
            ],
        ],
        'elements' => [
            [
                'type'    => 'switch',
                'data'    => 'bool',
                'key'     => 'pwa_enabled',
                'label'   => 'Enable PWA',
                'rules'   => 'required|boolean',
                'value'   => 1,
                'class'   => 'col-md-12',
                'message' => 'Master switch. When disabled, the manifest, service worker, install prompt, and offline support are turned off across user, merchant, and agent dashboards.',
            ],
            [
                'type'    => 'text',
                'data'    => 'string',
                'key'     => 'pwa_app_name',
                'label'   => 'App Name',
                'rules'   => 'nullable|string|max:60',
                'value'   => '',
                'class'   => 'col-md-6',
                'message' => 'Full name shown in the install dialog. Defaults to Site Title when empty.',
            ],
            [
                'type'    => 'text',
                'data'    => 'string',
                'key'     => 'pwa_short_name',
                'label'   => 'Short Name',
                'rules'   => 'nullable|string|max:12',
                'value'   => '',
                'class'   => 'col-md-6',
                'message' => 'Short label shown beside the icon on the home screen. Maximum 12 characters.',
            ],
            [
                'type'    => 'textarea',
                'data'    => 'string',
                'key'     => 'pwa_description',
                'label'   => 'App Description',
                'rules'   => 'nullable|string|max:200',
                'value'   => 'Secure mobile wallet dashboard.',
                'class'   => 'col-md-12',
                'message' => 'Short description shown by browsers and app catalogs.',
            ],
            [
                'type'    => 'color',
                'data'    => 'string',
                'key'     => 'pwa_theme_color',
                'label'   => 'Theme Color',
                'rules'   => 'required|regex:/^#[0-9A-Fa-f]{6}$/',
                'value'   => '#4663ee',
                'class'   => 'col-md-6',
                'message' => 'Hex color (e.g. #4663ee) used for the browser status bar in the installed app.',
            ],
            [
                'type'    => 'color',
                'data'    => 'string',
                'key'     => 'pwa_background_color',
                'label'   => 'Background Color',
                'rules'   => 'required|regex:/^#[0-9A-Fa-f]{6}$/',
                'value'   => '#f3f7fb',
                'class'   => 'col-md-6',
                'message' => 'Hex color shown on the splash screen while the app launches.',
            ],
            [
                'type'  => 'select',
                'data'  => 'string',
                'key'   => 'pwa_display',
                'label' => 'Display Mode',
                'rules' => 'required|in:standalone,fullscreen,minimal-ui,browser',
                'value' => 'standalone',
                'class' => 'col-md-3',
            ],
            [
                'type'  => 'select',
                'data'  => 'string',
                'key'   => 'pwa_orientation',
                'label' => 'Orientation',
                'rules' => 'required|in:any,portrait-primary,landscape-primary,portrait,landscape',
                'value' => 'portrait-primary',
                'class' => 'col-md-3',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'pwa_icon_192',
                'label' => 'Icon 192x192',
                'rules' => 'mimes:png|dimensions:width=192,height=192|max:1000',
                'value' => 'pwa/icons/icon-192.png',
                'class' => 'col-md-3',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'pwa_icon_512',
                'label' => 'Icon 512x512',
                'rules' => 'mimes:png|dimensions:width=512,height=512|max:1500',
                'value' => 'pwa/icons/icon-512.png',
                'class' => 'col-md-3',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'pwa_maskable_icon',
                'label' => 'Maskable Icon 512x512',
                'rules' => 'mimes:png|dimensions:width=512,height=512|max:1500',
                'value' => 'pwa/icons/maskable-512.png',
                'class' => 'col-md-3',
            ],
            [
                'type'  => 'img',
                'data'  => 'string',
                'key'   => 'pwa_apple_touch_icon',
                'label' => 'iOS Touch Icon 180x180',
                'rules' => 'mimes:png|dimensions:width=180,height=180|max:1000',
                'value' => 'pwa/icons/apple-touch-icon.png',
                'class' => 'col-md-3',
            ],
            [
                'type'  => 'textarea',
                'data'  => 'string',
                'key'   => 'pwa_offline_message',
                'label' => 'Offline Message',
                'rules' => 'nullable|string|max:500',
                'value' => 'A live connection is required for balances, payments, and transactions. Please reconnect and try again.',
                'class' => 'col-md-12',
            ],
            [
                'type'    => 'group_text',
                'data'    => 'string',
                'key'     => 'pwa_cache_version',
                'label'   => 'Cache Version Tag',
                'unit'    => 'tag',
                'rules'   => 'nullable|string|max:30',
                'value'   => '',
                'class'   => 'col-md-6',
                'message' => 'Bump this value (e.g. v2, v3, 2026-05-05) to force all installed apps to clear their cache and download fresh assets on next visit.',
            ],
        ],
    ],
    'hide_settings' => [
        'title'    => 'hide',
        'elements' => [
            [
                'data'  => 'bool',
                'key'   => 'deposit_rewards',
                'rules' => 'boolean',
                'value' => true,
            ],
            [
                'data'  => 'bool',
                'key'   => 'payment_rewards',
                'rules' => 'boolean',
                'value' => true,
            ],
        ],
    ],
];
